# Ignore system files
.git
.cache


# Ignore IDE/Editor folders
.vscode
.idea

# Ignore log files
logs
*.log

# Ignore configuration and secrets
.env
app/config/secrets.php
app/config/config-dev.php
phpunit.xml
docker.cnf
deployment.azure.yml

# Ignore PHP specific files
test.php
require-dev.php
composer-setup.php
secrets.php


# Ignore javascript files
*.js.map
*.min.intellisense.js
*.d.ts

# Ignore markdown files
*.md

# Ignore vendor files and directories
vendor
storage
sql-scripts

# Ignore cache
app/cache
/.phpunit.cache/

# Ignore test folders
app/unittests