name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push iuhrms image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-apache
          push: true
          tags: ecakubi/iuhrms:${{ substr(github.sha, 0, 7) }}

      - name: Build and push mysql image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-mysql
          push: true
          tags: ecakubi/mysql:${{ substr(github.sha, 0, 7) }}

      - name: Update deployment file with image tag for iuhrms
        run: |
            sed -i "s|ecakubi/iuhrms:latest|ecakubi/iuhrms:${{ substr(github.sha, 0, 7) }}|g" deployment.azure.yml

      - name: Update deployment file with image tag for mysql
        run: |
            sed -i "s|ecakubi/mysql:latest|ecakubi/mysql:${{ substr(github.sha, 0, 7) }}|g" deployment.azure.yml

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances (Container Group)
        run: |
          az container create --resource-group eastus-rg-01 \
            --file deployment.azure.yml

      - name: Azure Logout
        run: az logout
