name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get short SHA
        id: short_sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push iuhrms image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-apache
          push: true
          tags: ecakubi/iuhrms:${{ env.SHORT_SHA }}

      - name: Build and push mysql image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-mysql
          push: true
          tags: ecakubi/mysql:${{ env.SHORT_SHA }}

      - name: Update deployment file with image tag for iuhrms
        run: |
            sed -i "s|ecakubi/iuhrms:latest|ecakubi/iuhrms:${{ env.SHORT_SHA }}|g" deployment.azure.yml

      - name: Update deployment file with image tag for mysql
        run: |
            sed -i "s|ecakubi/mysql:latest|ecakubi/mysql:${{ env.SHORT_SHA }}|g" deployment.azure.yml

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances (Container Group)
        uses: Azure/arm-deploy@v1.0.9
        with:
          resourceGroupName: eastus-rg-01
          deploymentMode: Incremental
          template: deployment.azure.json
          parameters: parameters.deployment.azure.json

      - name: Azure Logout
        run: az logout
